### ISSUE TITLE
rnaseq-cgl-pipeline docker container grabs whole system

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/cgl-docker-lib#120]
The container starts by assessing the number of CPUs on the system and announces
`WARNING:toil.batchSystems.singleMachine:Limiting maxCores to CPU count of system (120).`

This is not advisable on shared systems. It's possible to limit the docker container itself, using 
`--cpuset-cpus=<cpu range>`, but this does not get forwarded to the docker containers that are started by the lead instance. This means that kallisto uses 100% of all CPUs when running on >10 samples, which is not a way to make friends...

**Comment by jvivian** [comment]
So I've thought about this and the `maxCores` toil option won't work for this use case either and I suspect it would cause a hang because currently the maximum number of cores for a job is determined by `multiprocessing.cpu_count`.  `maxCores` may set the limit to 32, but there would be jobs that are requesting 120 so they likely would never be scheduled. 

 I need to change cores to be something like `min(args.maxCores, multiprocssing.cpu_count())`, but I'll need to make the change to the pipeline source code first, then refactor the container to use that version of the RNA-seq pipeline.

**Comment by jvivian** [comment]
Requires BD2KGenomics/toil-scripts#283
