### ISSUE TITLE
“Hello World” for ADAM

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/cgl-docker-lib#13]
Same as #12, but run some simple ADAM-based transform
Run ADAM in same container as Spark master

**Comment by heuermh** [comment]
@hannes-ucsc @fnothaft Few questions here:
- Should the ADAM docker image build on top of the Spark docker image (so that calls forwarded by `adam-submit` to `spark-submit` happen in the same container)?
- Should we use the binary distribution (currently version [0.17.1](https://github.com/bigdatagenomics/adam/releases/tag/adam-parent_2.10-0.17.1)) for ADAM or build from git head?
- Do we need to build separate docker images for ADAM on Scala 2.10 and ADAM on Scala 2.11?

**Comment by fnothaft** [comment]
My apologies for the slow reply @heuermh ! I was OOO at meetings today.

> - Should the ADAM docker image build on top of the Spark docker image (so that calls forwarded by adam-submit to spark-submit happen in the same container)?

Yes, let's do this.

> - Should we use the binary distribution (currently version 0.17.1) for ADAM or build from git head?

I think we're going to run from git head for our experiments.

> - Do we need to build separate docker images for ADAM on Scala 2.10 and ADAM on Scala 2.11?

I would just build the 2.10 image. If someone is interested in a 2.11 image at a later date, we can upgrade/add a second image.

**Comment by almussel** [comment]
Closing this issue. We've got a successful hello world and we're onto bigger fish.
