### ISSUE TITLE
ADAM build fails due to not pushing spark-and-maven container

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/cgl-docker-lib#146]
```
docker build -no-cache -t quay.io/ucsc_cgl/adam-build:c251f79c6bde3dce12e685c6cf03d5b1c30e9273--6f908333f4002bdf047e81f8e1c8c25b083640ea . 
Warning: '-no-cache' is deprecated, it will be replaced by '--no-cache' soon. See usage.
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon 2.048 kB

Step 1 : FROM quay.io/ucsc_cgl/spark-and-maven:1.5.2.3.3.3-build
Pulling repository quay.io/ucsc_cgl/spark-and-maven
Tag 1.5.2.3.3.3-build not found in repository quay.io/ucsc_cgl/spark-and-maven
```

**Comment by fnothaft** [comment]
Also, something's failing when building that image anyways:

```
gzip: stdin: not in gzip format
[0m[91mtar: Child returned status 1[0m[91m
tar: Error is not recoverable: exiting now
[0mThe command '/bin/sh -c sh /home/download.sh' returned a non-zero code: 2
make: *** [runtime-container.DONE] Error 1
make: Nothing to be done for `test'.
```

@hannes-ucsc this is during the jenkins CI build. Why is the Jenkins build passing even with the Make error?

**Comment by hannes-ucsc** [comment]
I don't know. I think I mentioned this already: the build logic in that project needs some love. 

I don't think this is a Jenkins problem. I was aware that the build passes even though there are obvious failures. I suspect the problem is in `jenkins.py`. The twist here is that we don't want to abort the build on the first tool that fails to build. We want to continue to build other tools and then fail.

**Comment by fnothaft** [comment]
I have a fix for this coming up...
