### ISSUE TITLE
Tools added to quay.io via CI need to be public

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/cgl-docker-lib#34]

**Comment by jvivian** [comment]
Stuck on authentication.   I have the appropriate .dockercfg  with permissions to repos but getting a `403` from the POST request:

```
data = json.dumps({'visibility': 'public'})
r = requests.post('https://quay.io/api/v1/repository/ucsc_cgl/bwa/changevisibility', data)
>>> r
<Response [403]>
```

Ive tried also passing in auth=('user', 'pw') as a parameter to requests without luck.

**Comment by hannes-ucsc** [comment]
.dockercfg only affects Docker, not your own Python program or the Requests library.

You need to programmatically pass the credentials with your requests. Remember the tests we did the other day. Their documentation is spotty and out of date, it still mentions tokens even though they have been superseded by robot accounts.

Since the support was helpful, you could ask them for an example on how to authenticate a request with curl. I think it is something like `http://user:token@quay.io/...`

Whatever you end up doing to solve auth, don't hard-code credentials in the source code.
