### ISSUE TITLE
Fix requests bug in CI script on jenkins

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/cgl-docker-lib#43]
I assumed the version of python installed on jenkins would have an up-to-date _requests_ library, but it looks like it doesn't.

```
Making tool: ubu a publically visible repository.
Traceback (most recent call last):
  File "./jenkins.py", line 99, in <module>
    main()
  File "./jenkins.py", line 95, in main
    make_repos_public(tools_to_build, credentials=credentials)
  File "./jenkins.py", line 78, in make_repos_public
    response = requests.post(url, json=payload, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

This should be fixed by something like:

`requests.post(url, data=json.dumps(data), headers={"content-type": “application/json"))`

**Comment by hannes-ucsc** [comment]
Add a shell script called `jenkins.sh` that creates a virtualenv, installs the necessary dependencies and calls `jenkins.py`. This is how the Toil, CGCloud and S3AM builds work. The build would then be configured to source `jenkins.sh` rather than execute `jenkins.py`. I also changed my mind again about `jenkins.py`: I think it should be called `build.py` or `make.py`. Some people (@diekhans, for example) prefer not to have the `.py` extension and I would be find with that. The `.sh` extension to me always indicates a script that needs to be sourced rather than exec'ed so I would prefer `jenkins.sh` to maintain its extension since it needs to be sourced and can't be execed for Jenkins-specific reasons.

**Comment by jvivian** [comment]
My waffle hadn't updated when I closed this ticket so I missed your response.

The issue is currently fixed, but I could still setup a `jenkins.sh` (although there are no longer any dependencies that aren't satisfied by the docker-jenkins-slave role), which could make the call to build.py, but since it's not doing anything besides that it seems unnecessary.   What do you think?

In the Jenkins config I'm currently "execing" the script:  `./jenkins.py`, which runs the script in a new shell (as opposed to sourcing).  Is that also incorrect?

**Comment by hannes-ucsc** [comment]
How was the issue addressed? 

BTW: The resolution should always be recorded in the issue. Usually via comment referencing the commit. If your commit message ends in (resolves #...) GitHub will make that comment for you.

**Comment by jvivian** [comment]
Line 77,78: https://github.com/BD2KGenomics/cgl-docker-lib/commit/c7bca6fa63b787a0251a9b75cac26f20799150eb

> BTW: The resolution should always be recorded in the issue. Usually via comment referencing the commit. If your commit message ends in (resolves #...) GitHub will make that comment for you.

For some reason I only thought this was a feature of PRs not direct commits. I'll adopt this policy for all future tickets closed via commit.

**Comment by jvivian** [comment]
Can I close this @hannes-ucsc ?

**Comment by hannes-ucsc** [comment]
Yes.
